import os
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Load environment variables from .env file
load_dotenv()

# Set variables from environment variables
CLIENT_ID = os.getenv("SPOTIPY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIPY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIPY_REDIRECT_URI")

scope = "playlist-modify-private user-library-read"

sp_oauth = SpotifyOAuth(client_id=CLIENT_ID,
                        client_secret=CLIENT_SECRET,
                        redirect_uri=REDIRECT_URI,
                        scope=scope)

auth_url = sp_oauth.get_authorize_url()
print(f"Please navigate here: {auth_url}")

response = input("Enter the URL you were redirected to: ")
code = sp_oauth.parse_response_code(response)
token_info = sp_oauth.get_access_token(code)

sp = spotipy.Spotify(auth_manager=sp_oauth)

# Define the list of DJs
djs = [
    "¥ØU$UK€ ¥UK1MAT$U",
    "01001o11",
    "10 Mark DJ Team",
    "2 Girls 1 Club",
    "747",
    "Abramov",
    "Ace Ventura",
    "achtern",
    "Acidfinky",
    "Acidfinky in residence",
    "Acid Flora",
    "Acid Pauli",
    "Adana Twins",
    "add-us",
    "AFRO SLOT DJ SQUAD",
    "AGY3NA",
    "Ai Ris",
    "AKA NINA",
    "Akela Hi Powa",
    "AK SPORTS",
    "Alegria",
    "ALEJA",
    "Alek Lee",
    "Alexa D!saster",
    "Alexandra & Pirvu",
    "Alexa Play Music",
    "Alienata",
    "Alma Linda",
    "Aly Goede (nacelle, egypt)",
    "alys(alys)alys",
    "Anaconda ft. Doc Dressla",
    "Andi Otto",
    "Andrei Rusu",
    "Andy Loop",
    "ANËK",
    "Anja Schneider",
    "Ankytrixx",
    "Annika Threechords",
    "Anselmus",
    "any peach",
    "APHE",
    "Arlenys",
    "Arrogant und Anschmiegsam",
    "ASA 808",
    "Athenaïs",
    "Atzenever b2b Rave Dave b2b Scratch Babies",
    "Audiomatic",
    "audite",
    "Autre Gonzesse",
    "Aynaet",
    "Azpecialguest",
    "B2B CREW",
    "BadWolf",
    "Baja Frequencia",
    "Bamela Paywatch",
    "Bart Skils",
    "BASF",
    "Bassbabylon ft. Ras Free & Rapha Farma",
    "Bassface Sascha",
    "Baywatch United",
    "BB Deng",
    "BCSM",
    "Beneke",
    "Ben Klock",
    "Bernd Beton",
    "Beté",
    "Beth Lydi",
    "Bianca Oblivion",
    "Bianka Banks",
    "Billi DeStabl",
    "Bim",
    "Bisu b2b Maka",
    "Bitsy Knox",
    "Black Mirror Park",
    "Blame the Booker b2b 1/2 The Jakob Sisterz",
    "BLCK MAMBA",
    "BONUS w/ David Lenk b2b Barbaros",
    "Booty Terror",
    "Brian Cid",
    "Britta Arnold",
    "BRKN1",
    "Bruder Jakob",
    "Bryan Kessler",
    "Buunshin",
    "Ca$hmiri",
    "Caleesi & Sarah Kreis",
    "Carl Meinheit",
    "Carly Zeng",
    "Cassy",
    "Castora Herz",
    "CATELLE",
    "Catitha Steppah",
    "C&C Music",
    "Cincity",
    "Cinthie & MEAT",
    "Claudio Chinotto",
    "clean | cut",
    "Coco Cobra",
    "Coco Em",
    "Coco Loris",
    "coco pop",
    "Cocorosiescat",
    "Commander Love",
    "Credit 00",
    "Crew Ombrelle",
    "Crille & Tamalt",
    "Cyan85",
    "Dagga",
    "Da Iguana",
    "Daksinamurti",
    "Dale Rohan",
    "Dana Ruh",
    "Dandelion Soundsystem LS. Conscious Fiyah",
    "Daniel Imhof",
    "Daniel Krau",
    "Daniel Nitsch",
    "Dasco",
    "Dave Dinger & Avocado",
    "David Garage",
    "|D/A\W/A\ Collective",
    "Decibella & MC Chickaboo",
    "Dee Diggs",
    "Dépen:dance",
    "Derrick",
    "Dieter Flegel",
    "Dirty Clits",
    "Disco Collective",
    "Dj Anacaona",
    "DJ Ausbruch",
    "DJ BarbNerdy",
    "DJ Discotod",
    "DJ Fart in the Club",
    "DJ Fu",
    "Dj Jauche & Oliver Dollar",
    "DJ Koze",
    "DJ LESCH",
    "DJ MILLE b2b MOMO",
    "DJ NoSemos",
    "DJoanna",
    "DJ Perlé im Wrack",
    "Dj Real Madrid",
    "DJ Rise",
    "DJ Samet",
    "Dj Saudi",
    "DJ Sloush x Zarrt",
    "DJ Sprudel",
    "DJ Stingray 313",
    "DJ Sweet6teen",
    "DJ Tante Katha",
    "DJ Warnweste und Partyfässchen",
    "D-Nox",
    "Doc Dressla",
    "Dole & Kom",
    "Don Eule",
    "Donna Luetjen",
    "Dra. Gil",
    "Dranq",
    "Dr Calavera",
    "Dr. Rubinstein",
    "Drumbule",
    "Easy Hands aka Shape & Kaep",
    "Eggroni",
    "Eisen Josef",
    "Ele Luz",
    "Elif",
    "Elisa Elisa",
    "Eliza Feliz",
    "Elli Altenberger",
    "EL_P",
    "El Vago & Bongo (La Regla)",
    "Emok",
    "Erhardt Schuster",
    "Esshar",
    "Esther Silex",
    "Et Kin",
    "Eule:nhaupt & Molle:nhauer",
    "Fade Black",
    "Farmer Sound",
    "Femdelic",
    "FEM*SOUND CONNECTION",
    "Fereinwonung Koratien",
    "ferrari rot",
    "Finca Amour (Mimi Love & Franca)",
    "Finona Rider",
    "FNX Omar",
    "Four Seasons of Roots",
    "Fracture",
    "Franzi",
    "Franz Scala",
    "Freedu",
    "Frenetic",
    "Frida Darko & Atric",
    "Fritz Windish",
    "Frivolous",
    "FURIKURI",
    "Gefunkel",
    "Giulia Gutterer",
    "Giuseppe Leonardi",
    "GlutenfreeGhettoGirlz",
    "Goa Jonas",
    "Golanski",
    "Goodfella",
    "Gourski",
    "Gr33nhornZ",
    "Grawinkel",
    "Green Lake Project",
    "Guacamayo Tropical Dj's",
    "Gustav Krøne",
    "Gwen Wayne b2b Julio Paradise",
    "GypsyBox",
    "Haensen & Gretel",
    "Haghbin Dub",
    "Hägi & Mauler",
    "Hanaby",
    "Hanichiwa",
    "Hannes",
    "Hansi & Greta Bondage Massacre",
    "Hanzel",
    "Haptik & Kaptain Kosmo",
    "Heart XL",
    "Heimlich Knüller",
    "Heninspace",
    "Herrmann Stoehr",
    "High Speed Violence",
    "Hiroko Yamamura",
    "HOG",
    "HPTTRSN Punk DJs",
    "Hundread",
    "Hye-Eun Kim + Jakotako",
    "Hyperaktivist",
    "I Double m-o",
    "Inhärenz",
    "Innerlich Lea",
    "I Noah",
    "Intaktogene",
    "Internet_princess_91 X Uschi jagger",
    "Introversion",
    "Iron Curtis",
    "Isabelle Gaultiér",
    "Isadoser",
    "ISA GT",
    "Italian Dance Wave",
    "Italo Brutalo",
    "Ixindamix",
    "Jaamood",
    "Jackie Jackpot",
    "Jah Chalice Soundsystem",
    "Jahyoka",
    "Jaime Fiorito",
    "Jamiie & Fiona Kraft",
    "Jana Falcon",
    "Janthe",
    "Jascha Hagen",
    "Jeanette Trèsbien",
    "Jil Tanner",
    "Jimi Handtrix",
    "J:Kenzo",
    "JMCEE",
    "Joel Mull",
    "Johannes Albert",
    "Joney",
    "Juli N More",
    "Julio Paradise",
    "just emma",
    "Justice Rivah feat. Iyah Ranks & Galas",
    "Justine Perry",
    "Kaessrin",
    "Kaleema",
    "Karate Tschabi",
    "kassiopeia.",
    "Kataya",
    "Katzele b2b Menqui",
    "Kaufmann",
    "Kelle",
    "KiBotu",
    "kick´N´rush & Fog Puma",
    "Kiki Kokolores",
    "KILLA",
    "kim. b2b Samcho Panza",
    "kimchi cora",
    "Kimie",
    "Kim Jong Soul",
    "King E",
    "Kitty Amor",
    "Klackwerk",
    "Klaus Cuckoo",
    "Klaus Störtebretter",
    "Koane",
    "kobpy",
    "Kollektiv Fischmarkt b3b Laxberger",
    "Konfusia",
    "Kotoe",
    "KRAN",
    "Krawalle & Liebe",
    "Kristin Velvet",
    "Kronik",
    "La Loakai ft. MC Treasure Irie",
    "Lampé",
    "Lars Kracht",
    "Lars Noll b2b Felde",
    "LAU",
    "Lauri Minogue",
    "LawlessProd",
    "Lea Occhi",
    "Leeni & Danilo Kupfernagel",
    "le.fu",
    "Leika b2b Konrad Dycke",
    "Lemonella",
    "Lena Mega & LoA",
    "LENI",
    "Lenny Fuck",
    "Lisbird",
    "Lislbar & Wermuth",
    "Llasse",
    "Lotte Ahoi b2b BurnTale",
    "Louis Beton X Tars",
    "LUCINEE",
    "Luna City Express",
    "[lu:wers b2b Ingo Knito]",
    "LWT",
    "Maayan Nidam",
    "Madmotormiquel",
    "Mad Pitt",
    "Mads Mäusegerät",
    "Malu",
    "Malu b2b Suetszu",
    "Mami",
    "Mana & Bios",
    "Mandidextrous",
    "Mandrake",
    "Marcus Meinhardt",
    "Mareena",
    "Maria Theresia von Eberg",
    "Marie Midori",
    "Marliblue & Sofyah",
    "Marlon Hoffstadt b2b Malugi",
    "Mary Jane",
    "matildoutz",
    "MAUGLI",
    "Mazuko",
    "Meg10",
    "Mehr is Mehr",
    "Melie Mel",
    "mfj rulla",
    "Mia",
    "Mihai Pol",
    "Mikadho",
    "Mika Dutsch",
    "Mikal Aton",
    "Miley Serious",
    "militanzt",
    "militanzt",
    "Milou",
    "Mimizan",
    "mina losid",
    "Miniyme",
    "Mira and Chris Schwarzwalder",
    "mishy misch",
    "Miss Nansix",
    "Miss Tekix",
    "Mixtape Menage",
    "mobilegirl",
    "moiselle",
    "Mona Moore",
    "Mono Elekin",
    "Moonbase Soundsystem",
    "Mr. Ciao b2b ni:vek",
    "M.Rux",
    "Muadeep",
    "Mystery Affair",
    "Nadia Struiwigh",
    "Nadin & Nobody",
    "Naroma",
    "Nasra",
    "nassstya & Kardia",
    "Nas Tea",
    "Nastia",
    "Natalie Robinson",
    "Nathan Dawidowicz",
    "Nat Wendell",
    "Neele",
    "Neurologic",
    "Nikki Nair",
    "Nikki S",
    "Nina Hepburn",
    "Nixe",
    "Noa",
    "NONAPS",
    "Nonlocal Research",
    "Non+Ultras",
    "Nooel",
    "Novalu",
    "Numa Crew",
    "Ober Mannkind",
    "OBSTSALAT",
    "Oliver Huntemann",
    "Olivia Mendez b2b Reka Zalan",
    "Olivier Gobelet",
    "Oscar Der Winzige",
    "Pacaya",
    "Panivino",
    "Passage",
    "Pat Le Mandragore",
    "Pau",
    "Pavelo Promillo & Giorgio Inkasso",
    "Peachonfuse",
    "Pelin Vedis",
    "Perel",
    "Per Hammar",
    "Peter Groskreutz",
    "Phase & LaMeduza",
    "Philipp Fein",
    "Pinky Promise",
    "PoloRalf & LutzVuitton",
    "PONY b2b Multifun",
    "Populous",
    "Princess Room",
    "Punching Polly",
    "Pupa Vinz",
    "Q NANi",
    "Qnoe",
    "Rafael Aragon",
    "Rafush X Catu Diosis",
    "Ramona Wouters",
    "Raoul",
    "Ratchet",
    "Reckless",
    "Rena Volvo",
    "Robag Wruhme",
    "Roe Deers",
    "Ronja",
    "Roots Daughters",
    "Roots Descendents ft. Jon Moon & Ical Ises",
    "Rose Mild & Peter Pain",
    "RSS Disco",
    "Ryota Oi",
    "SAGAN",
    "Sallad Egg",
    "Salome",
    "Sama'",
    "Sanaz b2b Nesa Azadikhah",
    "Sandilé",
    "SANSIBAR",
    "Satta Dub",
    "Schmuuv",
    "Scorpio Qveen",
    "Sdunic & Klaus DJ",
    "Seahorse",
    "Sega Lee",
    "SELEKTOR BONY",
    "Set Ambessa",
    "Setaoc Mass",
    "SHA",
    "Shanti Disco",
    "Sherry b2b Slare",
    "shevvet",
    "Shorty Banks",
    "Sightiva Hifi",
    "Sims & May Din",
    "Sinamin",
    "Singles mit Niveau",
    "Siren Sisters ft. Treasure Irie",
    "Sis D",
    "sisi",
    "SKALA",
    "Skankstasy",
    "sk.mize",
    "Slic Unit",
    "Slimcase",
    "Smicki",
    "Soraya",
    "Spacer Woman",
    "Speckman",
    "S Ruston",
    "Stan Starry",
    "starssindamarsch",
    "Steve Bug",
    "Südseemelodien",
    "Supergloss",
    "Surf 2 Glory",
    "Surreal",
    "Suse b2b Elliver",
    "Sven Dohse",
    "Sven Weisemann",
    "Tanja Le Chains",
    "Taylor got Soul",
    "telva",
    "THC",
    "The Scout Wölfli Non-Stop Mega mix",
    "The Upbeats",
    "Tibi Dabo",
    "Timo Maas",
    "Tim Taste",
    "TKR & Monch MC",
    "TMSKDJ",
    "to be honest..",
    "Tony y Not",
    "Toroki & Isayah ft. Piyazawa",
    "Tranca Rua",
    "Trauma Mia",
    "Trixy House",
    "Try & Error",
    "Turmspringer",
    "TUTKU",
    "Uff",
    "Unknown Concept",
    "Upzet",
    "UTA",
    "Viikatory",
    "Vio PRG",
    "VUUDUU",
    "Wicked Corporation",
    "Willing Witness",
    "wisdom tits",
    "xD_Eric",
    "Yobovski & Valent",
    "YOEMAN",
    "Yooo Zoo a.k.a. DJ Oldschooltreff und DJ Yo_Ky",
    "Young Lychee & Dj Fucks Himself",
    "Young Marco",
    "Yungfya",
    "Yung Womb b2b NISSA",
    "Zayn Kemp",
    "ZITRONI",
    "Zunami",
    "Forum",
    "Bandbewerbungen",
    "Presse",
    "Kulturkosmos",
    "Kontakt",
    "Impressum",
    "Datenschutz",
    # Add more DJs as needed
]

# Create a new playlist
playlist_name = "Fusion Festival 2023 DJs Playlist"
playlist_description = "A collection of DJs that have played at Fusion Festival 2023"
user_id = sp.current_user()["id"]
playlist = sp.user_playlist_create(user_id, playlist_name, public=False, description=playlist_description)

# Search for each DJ and add them to the playlist
# Search for tracks by each DJ and add them to the playlist
for dj in djs:
    results = sp.search(q=f"artist:{dj}", type="track", limit=50)
    if results["tracks"]["items"]:
        track_uri = results["tracks"]["items"][0]["uri"]
        sp.playlist_add_items(playlist["id"], [track_uri])
    else:
        print(f"No tracks found for DJ '{dj}' on Spotify.")